# Generated by Django 6.0.6 on 2026-09-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='pin_code',
            field=models.CharField(blank=True, default='482917', help_text='6-digit client access PIN', max_length=10),
        ),
    ]
