# Generated by Django 6.0.6 on 2026-09-08 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_gallery_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, default='127.0.0.1', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('device_type', models.CharField(blank=True, default='Desktop Browser', max_length=60)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='galleries.gallery')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['gallery', '-viewed_at'], name='galleries_g_gallery_e9958d_idx'), models.Index(fields=['gallery', 'ip_address'], name='galleries_g_gallery_5dac27_idx')],
            },
        ),
    ]
