# Generated by Django 6.0.6 on 2026-09-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='invitation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
