# Generated by Django 6.0.6 on 2026-09-08 11:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_invitation_sent_at_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_token',
            field=models.CharField(blank=True, db_index=True, default=accounts.models.generate_dashboard_token, max_length=64),
        ),
    ]
