# Generated by Django 6.0.6 on 2026-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_dashboard_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=True, help_text="Whether the user's email address has been verified via Supabase or admin onboarding."),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_login_device',
            field=models.CharField(blank=True, default='Chrome on Windows', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent password update or reset.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of successful logins to this account.'),
        ),
    ]
