# Generated by Django 6.0.6 on 2026-09-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_is_email_verified_profile_last_login_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='studio_name',
            field=models.CharField(blank=True, default='', help_text='Custom studio brand name displayed in live client galleries and customer portals.', max_length=150),
        ),
    ]
