# Generated by Django 6.0.6 on 2026-09-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_studio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='studio_logo',
            field=models.ImageField(blank=True, help_text='Custom studio logo image displayed in settings and live client galleries.', null=True, upload_to='studio_logos/'),
        ),
    ]
