# Generated by Django 6.0.6 on 2026-09-08 19:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_uploaded_at(apps, schema_editor):
    Photo = apps.get_model('photos', 'Photo')
    from django.db.models import F
    Photo.objects.all().update(uploaded_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_cover_image'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='photos_phot_event_i_b01c1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='photos_phot_uploade_9afc8c_idx',
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.RunPython(populate_uploaded_at, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event', '-uploaded_at'], name='photos_phot_event_i_24a424_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='photos_phot_uploade_02e000_idx'),
        ),
    ]
